// <auto-generated />
using System;
using Ecommerce.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ecommerce.Migrations
{
    [DbContext(typeof(EcommerceContext))]
    [Migration("20191010064606_UserTableAdded")]
    partial class UserTableAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ecommerce.models.Department", b =>
                {
                    b.Property<int>("departmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("departmentImage");

                    b.Property<string>("departmentName");

                    b.HasKey("departmentId");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("Ecommerce.models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("creationDate");

                    b.Property<int>("departmentId");

                    b.Property<string>("productDescription");

                    b.Property<string>("productImage");

                    b.Property<int>("productMRP");

                    b.Property<string>("productName");

                    b.Property<int>("productPrice");

                    b.Property<int>("quantityAvailable");

                    b.Property<int>("quantitySold");

                    b.Property<DateTime>("updationDate");

                    b.HasKey("productId");

                    b.HasIndex("departmentId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Ecommerce.models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("userEmail");

                    b.Property<string>("userFirstName");

                    b.Property<string>("userLastName");

                    b.Property<string>("userMobile");

                    b.Property<string>("userPassword");

                    b.Property<string>("userRole");

                    b.HasKey("userId");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Ecommerce.models.Product", b =>
                {
                    b.HasOne("Ecommerce.models.Department", "Departments")
                        .WithMany()
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
